// src/routes/fractals/+page.svelte
<script lang="ts">
    import { PUBLIC_API_URL } from '$env/static/public';
    import Fa from 'svelte-fa/src/fa.svelte';
    import {
        faCheckCircle,
        faCircleNotch,
        faClipboard,
        faHouse,
    } from '@fortawesome/free-solid-svg-icons';
    import DesignatedPage from '$lib/components/DesignatedPage.svelte';
    import {
        DEFAULT_FRACTAL,
        COLORING_STRATEGY_LABELS,
        EXAMPLES,
        VARIATIONS,
        getFractal,
    } from '$lib/api/api.iapetus11.me/fractals';
    import type { Fractal } from '$lib/api/api.iapetus11.me/fractals';
    import { page } from '$app/stores';
    import { goto } from '$app/navigation';
    import { onMount } from 'svelte';

    const BUTTON_CLASSES =
        'flex fin py-2 px-2 sm:px-4 hover:bg-aqua-dark transform duration-100 border hover:border-opacity-0 ' +
        'border-white rounded-md h-8 sm:h-10 justify-center text-white w-full';

    let fractalUrl: string;
    let abortController: AbortController | null = null;
    let loading = true;
    let delayedLoadingTimeout = null;

    let fractal = Object.fromEntries(
        Object.entries(DEFAULT_FRACTAL).map(([k, v]) => [k, $page.url.searchParams.get(k) || v])
    ) as Fractal;

    async function updateQueryParams() {
        const url = new URL($page.url);

        Object.entries(fractal).forEach(([k, v]) => {
            if (v === undefined) url.searchParams.delete(k);
            else url.searchParams.set(k, `${v}`);
        });

        await goto(url);
    }

    async function load() {
        delayedLoadingTimeout = setTimeout(() => (loading = true), 200);

        try {
            await updateQueryParams();

            abortController?.abort();
            abortController = new AbortController();

            const fractalBlob = await getFractal(fractal, abortController.signal);

            fractalUrl = URL.createObjectURL(fractalBlob);
        } catch (error) {
            if (error.message === 'The user aborted a request.') return;
            throw error;
        } finally {
            clearTimeout(delayedLoadingTimeout);
            loading = false;
        }
    }

    let linkCopying = false;

    onMount(load);
</script>

<DesignatedPage>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4 justify-between">
        {#if !fractalUrl || loading}
            <div class="lg:order-2 flex self-center h-[93.5vw] lg:h-auto">
                <Fa
                    icon={faCircleNotch}
                    class="animate-spin self-center text-8xl text-gray-500 mx-auto"
                />
            </div>
        {:else}
            <img alt="fractal" src={fractalUrl} class="lg:order-2 rounded-lg shadow-xl w-full" />
        {/if}

        <div class="flex flex-col w-full gap-1.5 lg:gap-2 text-sm">
            <div class="flex gap-1.5 lg:gap-2">
                <button
                    type="button"
                    class={BUTTON_CLASSES}
                    class:bg-aqua-dark={linkCopying}
                    on:click={() => {
                        navigator.clipboard.writeText($page.url.toString());
                        linkCopying = true;
                        setTimeout(() => (linkCopying = false), 1000);
                    }}
                >
                    <Fa
                        icon={linkCopying ? faCheckCircle : faClipboard}
                        fw
                        class="self-center mr-1"
                    />
                    <span class="self-center">{linkCopying ? 'Copied!' : 'Copy Link'}</span>
                </button>

                <button
                    type="button"
                    class={BUTTON_CLASSES}
                    on:click={() => {
                        fractal = { ...DEFAULT_FRACTAL };
                        load();
                    }}
                >
                    <Fa icon={faHouse} fw class="self-center mr-1" />
                    <span class="self-center">Reset</span>
                </button>
            </div>

            <div class="grid grid-cols-12 gap-1.5 lg:gap-2">
                <label for="fractal-resolution-slider" class="col-span-10 sm:col-span-11">
                    Resolution
                </label>

                <label for="fractal-mirror-input" class="col-span-2 sm:col-span-1 text-center">
                    Mirror
                </label>

                <input
                    bind:value={fractal.resolution}
                    on:change={load}
                    class="col-span-10 sm:col-span-11"
                    id="fractal-resolution-slider"
                    type="range"
                    min={512}
                    max={2048}
                    step={256}
                />

                <input
                    bind:checked={fractal.mirrored}
                    on:change={load}
                    class="col-span-2 sm:col-span-1"
                    id="fractal-mirror-input"
                    type="checkbox"
                />
            </div>

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-variation-select">Variation</label>

                <label for="fractal-coloring-select">Coloring Mode</label>

                <select
                    bind:value={fractal.variation}
                    on:change={load}
                    id="fractal-variation-select"
                    class="text-black"
                >
                    {#each VARIATIONS as variation}
                        <option value={variation}>{variation}</option>
                    {/each}
                </select>

                <select
                    bind:value={fractal.coloring}
                    on:change={load}
                    id="fractal-coloring-select"
                    class="text-black"
                >
                    {#each COLORING_STRATEGY_LABELS as [name, coloringStrategy]}
                        <option value={coloringStrategy}>{name}</option>
                    {/each}
                </select>
            </div>

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-color-a-input">Primary Color</label>

                <label for="fractal-color-b-input">Secondary Color</label>

                <input
                    bind:value={fractal.colorA}
                    on:change={load}
                    class="w-full"
                    id="fractal-color-a-input"
                    type="color"
                />

                <input
                    bind:value={fractal.colorB}
                    on:change={load}
                    class="w-full"
                    id="fractal-color-b-input"
                    type="color"
                />
            </div>

            <label for="fractal-iter-transform-x-input">Iterative X Transform</label>
            <input
                bind:value={fractal.iterTransformX}
                on:change={load}
                id="fractal-iter-transform-x-input"
                type="range"
                min={0}
                max={1}
                step={0.03125}
            />

            <label for="fractal-iter-transform-y-input">Iterative Y Transform</label>
            <input
                bind:value={fractal.iterTransformY}
                on:change={load}
                id="fractal-iter-transform-y-input"
                type="range"
                min={0}
                max={1}
                step={0.03125}
            />

            <label for="fractal-iter-transform-input">Transform</label>
            <input
                bind:value={fractal.transform}
                on:change={load}
                id="fractal-iter-transform-input"
                type="range"
                min={0}
                max={1}
                step={0.03125}
            />

            <label for="fractal-x-shift-input">X Axis Shift</label>
            <input
                bind:value={fractal.xShift}
                on:change={load}
                id="fractal-x-shift-input"
                type="range"
                min={-1}
                max={1}
                step={0.0625}
            />

            <label for="fractal-iterations-input">Iterations</label>
            <input
                bind:value={fractal.iterations}
                on:change={load}
                id="fractal-iterations-input"
                type="range"
                min={100}
                max={50_00_000}
                step={100}
            />

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-blur-input">Blur</label>

                <label for="fractal-sharpen-input">Sharpen</label>

                <input
                    id="fractal-blur-input"
                    type="range"
                    value={fractal.blur || 0}
                    min={0}
                    max={4}
                    on:change={(event) => {
                        fractal.blur = parseInt(event.target.value) || undefined;
                        load();
                    }}
                />

                <input
                    id="fractal-sharpen-input"
                    type="range"
                    value={fractal.sharpen || 0}
                    min={0}
                    max={4}
                    on:change={(event) => {
                        fractal.sharpen = parseInt(event.target.value) || undefined;
                        load();
                    }}
                />
            </div>

            <p class="mt-3 text-sm">
                The
                <a
                    href="https://github.com/cuhackit-2022-patrickmakaylamichaelmilo/fractals/"
                    target="_blank"
                    rel="noreferrer"
                >
                    original code
                </a>
                behind these fractals was based off
                <a href="https://flam3.com/flame_draves.pdf" target="_blank" rel="noreferrer">
                    this paper
                </a>
                and conceived at
                <a href="https://cuhack.it/" target="_blank" rel="noreferrer">CUHackit 2022</a>
                by my team:
                <a
                    href="https://www.linkedin.com/in/michaelbyrd1/"
                    target="_blank"
                    rel="noreferrer"
                >
                    Michael Byrd</a
                >,
                <a href="https://makayla-moster.github.io/" target="_blank" rel="noreferrer">
                    Makayla Moster</a
                >, and
                <a href="https://patricksmathers.com/" target="_blank" rel="noreferrer">
                    Patrick Smathers</a
                >. Without them, this page would not be possible.
            </p>
            <p class="text-sm">
                Fractal images generated are licensed under a
                <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">
                    Creative Commons Attribution-ShareAlike 4.0 International License</a
                >.
            </p>
        </div>

        <div class="order-3 mt-4 lg:col-span-2">
            <h2 class="text-5xl">Gallery</h2>
            <p class="text-sm italic mt-1 ml-1">
                Clicking any of these images will load their parameters in above.
            </p>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-1.5 lg:gap-2 mt-4">
                {#each EXAMPLES as example}
                    <button
                        on:click={() => {
                            fractal = Object.fromEntries(new URLSearchParams(example).entries());
                            load();
                        }}
                    >
                        <img
                            src="{PUBLIC_API_URL}/fractals/?{example}"
                            alt="fractal example"
                            class="rounded-lg shadow-xl"
                        />
                    </button>
                {/each}
            </div>
        </div>
    </div>
</DesignatedPage>

// pages/fractals/index.vue
<script setup lang="ts">
    import {
        COLORING_STRATEGY_LABELS,
        DEFAULT_FRACTAL,
        EXAMPLES,
        type Fractal,
        FRACTAL_PARSER,
        VARIATIONS,
    } from '~/pages/fractals/fractals';
    import {
        faCheckCircle,
        faCircleNotch,
        faClipboard,
        faHouse,
    } from '@fortawesome/free-solid-svg-icons';
    import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
    import { parseQueryParams } from '~/utils/queryParamsParser';

    definePageMeta({
        title: 'Fractals',
    });

    const {
        public: { API_BASE_URL },
    } = useRuntimeConfig();
    const router = useRouter();
    const route = useRoute();

    const fractalConfig = ref<Fractal>(DEFAULT_FRACTAL);

    // Sync fractalConfig to query params
    watch(
        fractalConfig,
        (fc) => {
            const serialized = Object.fromEntries(
                Object.entries(fc).map(([k, v]) => [k, `${v}`])
            ) as Record<string, string>;
            router.replace({ query: { ...route.query, ...serialized } });
        },
        { deep: true }
    );

    // Sync query params to fractalConfig
    watch(
        () => route.query,
        (queryParams) => {
            fractalConfig.value = parseQueryParams(
                queryParams as Record<string, string>,
                FRACTAL_PARSER,
                DEFAULT_FRACTAL
            );
        },
        { deep: true, immediate: true }
    );

    const fractal = reactive(
        await useFetch(`${API_BASE_URL}/fractals`, {
            query: computed(() =>
                Object.fromEntries(
                    Object.entries(fractalConfig.value).filter(([k, v]) => {
                        if (v === undefined) {
                            return false;
                        }

                        if (['blur', 'sharpen'].includes(k)) {
                            return v !== 0;
                        }

                        return true;
                    })
                )
            ),
            transform: URL.createObjectURL,
            server: false,
            lazy: true,
        })
    );

    const linkCopied = ref(false);
    function copyLinkToFractal() {
        navigator.clipboard.writeText(window.location.toString());
        linkCopied.value = true;
        setTimeout(() => (linkCopied.value = false), 1000);
    }

    function resetFractal() {
        fractalConfig.value = { ...DEFAULT_FRACTAL };
    }
</script>

<template>
    <div class="grid grid-cols-1 justify-between gap-4 text-white lg:-mx-6 lg:grid-cols-2">
        <!-- Fractal display / loading -->
        <div class="flex aspect-square w-full items-center justify-center lg:order-2">
            <FontAwesomeIcon
                v-if="fractal.pending"
                :icon="faCircleNotch"
                class="animate-spin text-8xl text-gray-500"
            />
            <img v-else-if="fractal.data" :src="fractal.data!" alt="Fractal" class="rounded-xl" />
        </div>

        <!-- Fractal config -->
        <div class="flex w-full flex-col gap-1.5 text-sm lg:gap-2">
            <div class="flex gap-1.5 lg:gap-2">
                <button
                    type="button"
                    class="button col-span-6 w-full"
                    :class="{ 'bg-aqua-dark': linkCopied }"
                    @click="copyLinkToFractal"
                >
                    <FontAwesomeIcon
                        :icon="linkCopied ? faCheckCircle : faClipboard"
                        fixed-width
                        class="mr-1 self-center"
                    />
                    <span class="self-center">{{ linkCopied ? 'Copied!' : 'Copy Link' }}</span>
                </button>

                <button type="button" class="button col-span-6 w-full" @click="resetFractal">
                    <FontAwesomeIcon :icon="faHouse" fixed-width class="mr-1 self-center" />
                    <span class="self-center">Reset</span>
                </button>
            </div>

            <div class="grid grid-cols-12 gap-1.5 lg:gap-2">
                <label for="fractal-resolution-slider" class="col-span-10 sm:col-span-11">
                    Resolution
                </label>

                <label for="fractal-mirror-input" class="col-span-2 text-center sm:col-span-1">
                    Mirror
                </label>

                <input
                    id="fractal-resolution-slider"
                    v-model.number="fractalConfig.resolution"
                    class="col-span-10 sm:col-span-11"
                    type="range"
                    min="512"
                    max="2048"
                    step="256"
                />

                <input
                    id="fractal-mirror-input"
                    v-model="fractalConfig.mirrored"
                    class="col-span-2 sm:col-span-1"
                    type="checkbox"
                />
            </div>

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-variation-select">Variation</label>

                <label for="fractal-coloring-select">Coloring Mode</label>

                <select
                    id="fractal-variation-select"
                    v-model="fractalConfig.variation"
                    class="text-black"
                >
                    <option v-for="variation in VARIATIONS" :key="variation" :value="variation">
                        {{ variation }}
                    </option>
                </select>

                <select
                    id="fractal-coloring-select"
                    v-model="fractalConfig.coloring"
                    class="text-black"
                >
                    <option
                        v-for="[name, coloringStrategy] in COLORING_STRATEGY_LABELS"
                        :key="coloringStrategy"
                        :value="coloringStrategy"
                    >
                        {{ name }}
                    </option>
                </select>
            </div>

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-color-a-input">Primary Color</label>

                <label for="fractal-color-b-input">Secondary Color</label>

                <input
                    id="fractal-color-a-input"
                    v-model="fractalConfig.colorA"
                    class="w-full"
                    type="color"
                />

                <input
                    id="fractal-color-b-input"
                    v-model="fractalConfig.colorB"
                    class="w-full"
                    type="color"
                />
            </div>

            <label for="fractal-iter-transform-x-input">Iterative X Transform</label>
            <input
                id="fractal-iter-transform-x-input"
                v-model.number="fractalConfig.iterTransformX"
                type="range"
                min="0"
                max="1"
                step="0.03125"
            />

            <label for="fractal-iter-transform-y-input">Iterative Y Transform</label>
            <input
                id="fractal-iter-transform-y-input"
                v-model.number="fractalConfig.iterTransformY"
                type="range"
                min="0"
                max="1"
                step="0.03125"
            />

            <label for="fractal-iter-transform-input">Transform</label>
            <input
                id="fractal-iter-transform-input"
                v-model.number="fractalConfig.transform"
                type="range"
                min="0"
                max="1"
                step="0.03125"
            />

            <label for="fractal-x-shift-input">X Axis Shift</label>
            <input
                id="fractal-x-shift-input"
                v-model="fractalConfig.xShift"
                type="range"
                min="-1"
                max="1"
                step="0.0625"
            />

            <label for="fractal-iterations-input">Iterations</label>
            <input
                id="fractal-iterations-input"
                v-model.number="fractalConfig.iterations"
                type="range"
                min="100"
                max="5000000"
                step="100"
            />

            <div class="grid grid-cols-2 gap-1.5 lg:gap-2">
                <label for="fractal-blur-input">Blur</label>

                <label for="fractal-sharpen-input">Sharpen</label>

                <input
                    id="fractal-blur-input"
                    v-model.number="fractalConfig.blur"
                    type="range"
                    min="0"
                    max="4"
                />

                <input
                    id="fractal-sharpen-input"
                    v-model.number="fractalConfig.sharpen"
                    type="range"
                    min="0"
                    max="4"
                />
            </div>

            <p class="mt-3 text-sm">
                The
                <a
                    href="https://github.com/cuhackit-2022-patrickmakaylamichaelmilo/fractals/"
                    target="_blank"
                    rel="noreferrer"
                    class="text-link"
                >
                    original code
                </a>
                behind these fractals was based off
                <a
                    href="https://flam3.com/flame_draves.pdf"
                    target="_blank"
                    rel="noreferrer"
                    class="text-link"
                >
                    this paper
                </a>
                and conceived at
                <a href="https://cuhack.it/" target="_blank" rel="noreferrer" class="text-link"
                    >CUHackit 2022</a
                >
                by me and my team:
                <a
                    href="https://www.linkedin.com/in/michaelbyrd1/"
                    target="_blank"
                    rel="noreferrer"
                    class="text-link"
                >
                    Michael Byrd</a
                >,
                <a
                    href="https://makayla-moster.github.io/"
                    target="_blank"
                    rel="noreferrer"
                    class="text-link"
                >
                    Makayla Moster</a
                >, and
                <a
                    href="https://patricksmathers.com/"
                    target="_blank"
                    rel="noreferrer"
                    class="text-link"
                >
                    Patrick Smathers</a
                >. Without them, this page would not be possible.
            </p>
            <p class="text-sm">
                Fractal images generated are licensed under a
                <a
                    rel="license"
                    target="_blank"
                    href="https://creativecommons.org/licenses/by-sa/4.0/"
                    class="text-link"
                >
                    Creative Commons Attribution-ShareAlike 4.0 International License</a
                >.
            </p>
        </div>

        <div class="order-3 mt-4 lg:col-span-2">
            <h2 class="text-5xl">Gallery</h2>
            <p class="ml-1 mt-1 text-sm italic">
                Clicking any of these images will load their parameters in above.
            </p>

            <div class="mt-4 grid grid-cols-1 gap-1.5 md:grid-cols-2 lg:grid-cols-3 lg:gap-2">
                <button v-for="example in EXAMPLES" :key="example" type="button">
                    <img
                        :src="`${API_BASE_URL}/fractals/?${example}`"
                        alt="fractal example"
                        class="rounded-lg shadow-xl"
                        loading="lazy"
                    />
                </button>
            </div>
        </div>
    </div>
</template>
