// pages/projects/index.vue
<script setup lang="ts">
    import Project from '~/components/Project.vue';
    import { PROJECTS } from '~/data/projects';

    definePageMeta({
        title: 'Projects',
    });

    defineRouteRules({
        prerender: true,
    });
</script>

<template>
    <div class="grid grid-cols-1 gap-4 sm:gap-7 md:gap-10 lg:grid-cols-2 lg:max-xl:-mx-10">
        <Project
            v-for="(project, idx) in PROJECTS"
            v-bind="project"
            :key="project.name"
            class="animate-fade-in"
            :style="`animation-delay: ${idx * 50}ms`"
        />
    </div>
</template>

// src/routes/projects/+page.svelte
<script lang="ts">
    import { projects } from '$lib/data/me.ts';
    import DesignatedPage from '$lib/components/DesignatedPage.svelte';

    import ProjectCard from './ProjectCard.svelte';
</script>

<DesignatedPage title="Projects">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-3 md:gap-6 lg:gap-12 xl:mx-6">
        {#each projects as project, idx}
            <ProjectCard {...project} {idx} />
        {/each}
    </div>
</DesignatedPage>
